include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/flutter/**"
    - "**/flutter_devicelab/**"
    - "**/dev/**"
    - "**/test/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Игнорировать предупреждения о deprecated
    deprecated_member_use: ignore
    # Игнорировать предупреждения о неиспользуемых импортах
    unused_import: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types

