// Code generated by gobind. DO NOT EDIT.

// Java class libXray.libXray.DialerController is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=libXray github.com/amnezia-vpn/amnezia-libxray
package libXray.libXray;

import go.Seq;

public interface DialerController {
	public boolean protectFd(long p0);
	
}

